apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Chart.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.api.name }}
rules:
- apiGroups:
  - '*'
  resources:
  - pods
  - jobs
  verbs:
  - list
  - get
  - create
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.api.name }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Chart.Name }}
  name: {{ .Values.api.name }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.api.name }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Chart.Name }}
  labels:
    scanning-api: {{ .Values.api.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      scanning-api: {{ .Values.api.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/pod: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      labels:
        scanning-api: {{ .Values.api.name }}
    spec:
      serviceAccount: {{ .Values.api.name }}
      containers:
        - imagePullPolicy: {{ .Values.api.imagePullPolicy }}
          image: {{ .Values.api.image }}
          name: {{ .Values.api.name }}
          env:
            - name: IMAGE_SCANNER
              value: {{ .Values.api.imageScanner }}
            - name: PRIVATE_IMAGE_HUB_NAME
              value: {{ .Values.private_image_hub.name }}
            - name: PRIVATE_CR_SECRET_NAME
              value: {{ .Values.private_image_hub.secret_name }}
            - name: RUN_IN_NAMESPACE
              value: {{ .Chart.Name }}
            - name: SERVICE_ENDPOINT
              value: {{ .Values.api.name }}
            - name: SQL_USER
              value: {{ .Values.db.user }}
            - name: SQL_DATABASE
              value: {{ .Values.db.database }}
            - name: SQL_SERVER
              value: {{ .Values.db.server }}
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SQL_PASSWORD
                  name: {{ .Values.db.secret_name }}
          ports:
            - containerPort: {{ .Values.api.port }}
              name: http
              protocol: TCP
          # resources:
          #   limits:
          #     cpu: "1"
          #     memory: 516Mi
          #   requests:
          #     cpu: "1"
          #     memory: 516Mi
          securityContext:
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Chart.Name }}
  labels:
    component: {{ .Values.api.name }}
spec:
  ports:
  - name: http
    port: {{ .Values.api.port }}
    protocol: TCP
    targetPort: {{ .Values.api.port }}
  selector:
    scanning-api: {{ .Values.api.name }}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: {{ .Values.api.name }}
  name: {{ .Values.api.name }}
  namespace: {{ .Chart.Name }}
spec:
  endpoints:
  - interval: 15s
    port: http
  jobLabel: {{ .Values.api.name }}
  namespaceSelector:
    matchNames:
    - {{ .Chart.Name }}
  selector:
    matchLabels:
      component: {{ .Values.api.name }}
---
