apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.scan_vulnerabilities_job.name }}
  namespace: {{ .Chart.Name }}
spec:
  schedule: {{ .Values.scan_vulnerabilities_job.schedule }}
  concurrencyPolicy: {{ .Values.scan_vulnerabilities_job.concurrencyPolicy }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: callout
            image: buildpack-deps:curl
            args:
            - /bin/sh
            - -ec
            - curl -X POST http://scanning-api:8080/runs
          restartPolicy: Never