apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: image-scanner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-scanner
rules:
- apiGroups:
  - '*'
  resources:
  - pods
  verbs:
  - list
  - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-scanner
subjects:
- kind: ServiceAccount
  namespace: image-scanner
  name: api
roleRef:
  kind: ClusterRole
  name: image-scanner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanning-api
  namespace: image-scanner
  labels:
    scanning-api: scanning-api
spec:
  replicas: 1
  selector:
    matchLabels:
        scanning-api: scanning-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/pod: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      labels:
        scanning-api: scanning-api
    spec:
      serviceAccount: api
      containers:
        - imagePullPolicy: Always
          image: radixdev.azurecr.io/security-scanner-api:keaaa-9
          name: scanning-api
          env:
            - name: SQL_USER
              value: radix
            - name: SQL_DATABASE
              value: sqldb-radix-image-vul
            - name: SQL_SERVER
              value: sql-radix-image-vul-dev.database.windows.net
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SQL_PASSWORD
                  name: sql-cred
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          # resources:
          #   limits:
          #     cpu: "1"
          #     memory: 516Mi
          #   requests:
          #     cpu: "1"
          #     memory: 516Mi
          securityContext:
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: scanning-api
  namespace: image-scanner
  labels:
    component: scanning-api
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    scanning-api: scanning-api
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: radix-stage1
  name: scanning-api
  namespace: image-scanner
spec:
  endpoints:
  - interval: 15s
    port: http
  jobLabel: scanning-api
  namespaceSelector:
    matchNames:
    - image-scanner
  selector:
    matchLabels:
      component: scanning-api
---
