apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: image-vulnerability-db
  namespace: image-scanner
  labels:
    image-scanner: image-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      image-scanner: image-scanner
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/pod: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      labels:
        image-scanner: image-scanner
    spec:
      automountServiceAccountToken: false
      containers:
        - imagePullPolicy: Always
          image: keaaa/image-vulnerability-db
          name: image-vulnerability-db
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          # resources:
          #   limits:
          #     cpu: "1"
          #     memory: 516Mi
          #   requests:
          #     cpu: "1"
          #     memory: 516Mi
          securityContext:
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: image-vulnerability-db
  namespace: image-scanner
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    image-scanner: image-scanner
  sessionAffinity: None
  type: ClusterIP