apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scanning-api
  namespace: image-scanner
  labels:
    scanning-api: scanning-api
spec:
  replicas: 2
  selector:
    matchLabels:
        scanning-api: scanning-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        apparmor.security.beta.kubernetes.io/pod: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      labels:
        scanning-api: scanning-api
    spec:
      automountServiceAccountToken: false
      containers:
        - imagePullPolicy: Always
          image: keaaa/scanning-api
          name: scanning-api
          env:
            - name: AZURE_STORAGE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: AZURE_STORAGE_ACCOUNT
                  name: azure-storage-account
            - name: AZURE_STORAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AZURE_STORAGE_ACCESS_KEY
                  name: azure-storage-account
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          # resources:
          #   limits:
          #     cpu: "1"
          #     memory: 516Mi
          #   requests:
          #     cpu: "1"
          #     memory: 516Mi
          securityContext:
            allowPrivilegeEscalation: false
