apiVersion: v1
kind: Service
metadata:
  name: scanning-api
  namespace: image-scanner
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    scanning-api: scanning-api
  sessionAffinity: None
  type: ClusterIP