apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: callout
  namespace: image-scanner
spec:
  schedule: "45 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: callout
            image: buildpack-deps:curl
            args:
            - /bin/sh
            - -ec
            - curl -X POST http://scanning-api:8080/runs
          restartPolicy: Never