# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

vulnerability_db:
    name: vulnerability-db
    port: 8080
    image: keaaa/image-vulnerability-db
    imagePullPolicy: Always

scan_vulnerabilities_job:
    name: scan-vulnerabilities
    schedule: "45 * * * *"
    concurrencyPolicy: Forbid
    restartPolicy: Never

api:
    name: vulnerability-api
    image: radixdev.azurecr.io/security-scanner-api:keaaa-10
    imagePullPolicy: Always
    port: 8080

private_image_hub:
    secret_name: private-image-hub
    username: xxx
    password: xxx

db:
    secret_name: sql-credentials
    user: radix
    database: xxx
    server: xxx
    password: xxx
  
oauth:
    secret_name: oauth
    client_id: xxx
    cookie_secret: xxx
    cookie_secret: xxx
